const stockProductos = [
    {
      id: 1,
      nombre: "Manga One Punch Man",
      cantidad: 1,
      desc: "Es la temporada, completa de 'One punch man'",
      precio: 1200,
      img: "img/onePunch.webp",
    },
    {
      id: 2,
      nombre: "Manga Attack On Titan",
      cantidad: 1,
      desc: "La tepotada, completa de a 'Attack On Titan'",
      precio: 1500,
      img: "img/attakOnTittan.jpg",
    },
    {
      id: 3,
      nombre: "Manga Dragon Ball S",
      cantidad: 1,
      desc: "Temporada, completa de 'Dragon Ball Super'",
      precio: 1570,
      img: "img/dragonball.jpg",
    },
    {
      id: 4,
      nombre: "Manga Naruto",
      cantidad: 1,
      desc: "Temporada, completa de 'Naruto'",
      precio: 1000,
      img: "img/Naruto.jpg",
    },
    {
      id: 5,
      nombre: "Manga Blue Lock",
      cantidad: 1,
      desc: "Temporada, completa de 'Blue Lock'",
      precio: 1200,
      img: "img/blueLock.jpg",
    },
    {
      id: 6,
      nombre: "Manga Death Note",
      cantidad: 1,
      desc: "Temporada, completa de 'Death Note'",
      precio: 1200,
      img: "img/deathNote.jpg",
    },
    {
      id: 7,
      nombre: "Couch de League of Legends",
      cantidad: 1,
      desc: "No compres esto por tu bien",
      precio: 1400,
      img: "img/maestroprofesorinstructor.jpeg",
    },
    {
      id: 8,
      nombre: "Duende Tuneado",
      cantidad: 1,
      desc: "Es un duende tuneado que mas queres",
      precio: 100000000,
      img: "img/duendeTuneado.webp",
    },
    {
      id: 9,
      nombre: "Mate de escorpion",
      cantidad: 1,
      desc: "Mate de escorpion por tiempo limitado",
      precio: 140,
      img: "img/escorpionMate.jpg",
    },
    {
      id: 10,
      nombre: "Capibara Hincha de Boca",
      cantidad: 1,
      desc: "Na flaco no vas a comprar un capibara de boquita",
      precio: 1200,
      img: "img/capibaraBoca.webp",
    },
  ];